#!/system/bin/sh
#
# @kn8wolf 
#

tune2fs -o journal_data_writeback /dev/block/platform/msm_sdcc.1/by-name/system
tune2fs -O ^has_journal /dev/block/platform/msm_sdcc.1/by-name/system
tune2fs -o journal_data_writeback /dev/block/platform/msm_sdcc.1/by-name/cache
tune2fs -O ^has_journal /dev/block/platform/msm_sdcc.1/by-name/cache
tune2fs -o journal_data_writeback /dev/block/platform/msm_sdcc.1/by-name/userdata
tune2fs -O ^has_journal /dev/block/platform/msm_sdcc.1/by-name/userdata

echo "0" > /proc/sys/vm/swappiness;

echo "10" > /proc/sys/vm/vfs_cache_pressure; 

echo "9000" > /proc/sys/vm/dirty_writeback_centisecs;

echo "5000" > /proc/sys/vm/dirty_expire_centisecs; 

#echo "0" > /proc/sys/vm/dirty_writeback_centisecs;

#echo "20" > /proc/sys/vm/dirty_expire_centisecs; 

echo "0" > /proc/sys/vm/laptop_mode; 
echo "90" > /proc/sys/vm/dirty_ratio; 
echo "85" > /proc/sys/vm/dirty_background_ratio;  

echo "0" > /proc/sys/vm/oom_kill_allocating_task;  
echo "8" > /proc/sys/vm/page-cluster; 
echo "4096" > /proc/sys/vm/vm.min_free_kbytes; 
echo "0" > /proc/sys/vm/panic_on_oom; 
echo "64000" > /proc/sys/kernel/msgmni;
echo "64000" > /proc/sys/kernel/msgmax;
echo "10" > /proc/sys/fs/lease-break-time;

echo "0" > /proc/sys/net/ipv4/tcp_timestamps; 
echo "1" > /proc/sys/net/ipv4/tcp_tw_reuse; 
echo "1" > /proc/sys/net/ipv4/tcp_sack; 
echo "1" > /proc/sys/net/ipv4/tcp_tw_recycle; 
echo "1" > /proc/sys/net/ipv4/tcp_window_scaling; 
echo "5" > /proc/sys/net/ipv4/tcp_keepalive_probes; echo "30" > /proc/sys/net/ipv4/tcp_keepalive_intvl; 
echo "30" > /proc/sys/net/ipv4/tcp_fin_timeout; 
echo "404480" > /proc/sys/net/core/wmem_max; 
echo "404480" > /proc/sys/net/core/rmem_max; 
echo "256960" > /proc/sys/net/core/rmem_default; 
echo "256960" > /proc/sys/net/core/wmem_default; 
echo "4096,16384,404480" > /proc/sys/net/ipv4/tcp_wmem; 
echo "4096,87380,404480" > /proc/sys/net/ipv4/tcp_rmem;

renice -- -20 `pidof com.android.phone`
renice -- -17 `pidof com.android.systemui`
renice -- -15 `pidof ginlemon.flowerpro`
renice -- -9 `pidof com.android.vending`
renice -- -3 `pidof android.process.media`

for i in \
`busybox find /data -iname "*.db"`; 
do \
	/system/xbin/sqlite3 $i 'VACUUM;'; 
	/system/xbin/sqlite3 $i 'REINDEX;'; 
done;

if [ -d "/dbdata" ]; then
	for i in \
	`busybox find /dbdata -iname "*.db"`; 
	do \
		/system/xbin/sqlite3 $i 'VACUUM;'; 
		/system/xbin/sqlite3 $i 'REINDEX;'; 
	done;
fi;

if [ -d "/datadata" ]; then
	for i in \
	`busybox find /datadata -iname "*.db"`; 
	do \
		/system/xbin/sqlite3 $i 'VACUUM;'; 
		/system/xbin/sqlite3 $i 'REINDEX;'; 
	done;
fi;

for i in \
`busybox find /sdcard -iname "*.db"`; 
do \
	/system/xbin/sqlite3 $i 'VACUUM;'; 
	/system/xbin/sqlite3 $i 'REINDEX;'; 
done;

busybox mount -o remount,noatime,noauto_da_alloc,nodiratime,barrier=0,nobh /system 
busybox mount -o remount,noatime,noauto_da_alloc,nosuid,nodev,nodiratime,barrier=0,nobh /data 
busybox mount -o remount,noatime,noauto_da_alloc,nosuid,nodev,nodiratime,barrier=0,nobh /cache
